### ISSUE TITLE
deploy docker container with flask server and a simple html/js website

### ISSUE THREAD

**Issue by rtalwar2** [osoc22/technical-support#11]
**Describe the solution you'd like**
we need help to deploy our project on digital ocean or use the debian server

**Describe alternatives you've considered**
deploying the project at home on my rpi and then portforwarding

**Comment by jbelien** [comment]
Hello @rtalwar2 ,

Do you have a `Dockerfile` ready in your repository ?

**Comment by rtalwar2** [comment]
yes but the port is exposed on commandline with -p 5000:5000, is that okay?

**Comment by jbelien** [comment]
Shouldn't be an issue!

🚀 Here it is: https://the-impact-of-sharing-knowledge.osoc.be/

```yaml
domains:
- domain: api.the-impact-of-sharing-knowledge.osoc.be
  type: PRIMARY
  zone: osoc.be
name: the-impact-of-sharing-knowledge
region: ams
services:
- dockerfile_path: Dockerfile
  github:
    branch: master
    deploy_on_push: true
    repo: osoc22/project-the-power-of-sharing-knowledge
  http_port: 5000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: the-impact-of-sharing-knowledge
  routes:
  - path: /
  source_dir: /
```
