### ISSUE TITLE
automatic deployment not working?

### ISSUE THREAD

**Issue by rtalwar2** [osoc22/technical-support#20]
**Is your request related to a problem? Please describe.**
yesterday evening we decided to change the name of our repository from "project-the-power-of-sharing-knowledge" to "project-knowledge-impact". Is it possible that the automatic deployment has to be reconfigured? Because I fixed some bugs locally but it looks like they don't get pushed to the deployed server. 

**Describe the solution you'd like**
check if the name change caused the automatic deployment to fail

**Describe alternatives you've considered**
deploying on my rpi at home and portforwarding

**Comment by jbelien** [comment]
@rtalwar2 Yes, of course!

Auto-deploy is connected to your GitHub repository.
If you changed the name of the repository, that link is of course broken.
I'll try to fix it during the day.

**Comment by jbelien** [comment]
Configuration has been updated:
```yaml
domains:
- domain: api.the-impact-of-sharing-knowledge.osoc.be
  type: PRIMARY
  zone: osoc.be
- domain: api.knowledge-impact.osoc.be
  type: ALIAS
  zone: osoc.be
name: knowledge-impact
region: ams
services:
- dockerfile_path: Dockerfile
  github:
    branch: master
    deploy_on_push: true
    repo: osoc22/project-knowledge-impact
  http_port: 5000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: knowledge-impact
  routes:
  - path: /
  source_dir: /
```

Auto-deployment is back online!
