### ISSUE TITLE
Change branch for Digital Ocean App Platform docker image

### ISSUE THREAD

**Issue by Matei9721** [osoc22/technical-support#9]
**Is your request related to a problem? Please describe.**
We deployed our backend a week ago, but it was from a different branch. We have now merged everything with main so we want to choose the branch listed in Digital Ocean App Platform to main.

**Describe the solution you'd like**
This is the docker file on the main branch: https://github.com/osoc22/project-idlab/blob/master/app/backend/Dockerfile

**Additional context**

We were instructed to ping @jbelien for the change process. Thank you! :)

Team is IDLab: https://help.osoc.be/osoc22/projects-partners/idlab

**Comment by jbelien** [comment]
Configuration has been updated:
```yaml
name: idlab
region: ams
services:
- dockerfile_path: app/backend/Dockerfile
  github:
    branch: master
    deploy_on_push: true
    repo: osoc22/project-idlab
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: project-idlab-backend
  routes:
  - path: /
  source_dir: app/backend
```
